### ISSUE TITLE
function emu.getscreenpixel returns single integer?

### ISSUE THREAD

**Issue by kulbhushanchand** [spiiin/fceux_luaserver#1]
**Thanks for creating this repo.**

I have created this issue so this comment (https://github.com/TASVideos/fceux/issues/22#issuecomment-449035494) may not get unnoticed.

The `emu.getscreenpixel` shoud return rgb values- 

![image](https://user-images.githubusercontent.com/17742733/50750744-5f879600-126c-11e9-9bdd-3f77dd0779ef.png)

**Comment by spiiin** [comment]
fixed in commit
https://github.com/spiiin/fceux_luaserver/commit/8daf917ea1392ff66b9929824965aa33c4006384
